.github/workflows/ci.yml
.github/workflows/pr-title-validation.yml
app/build.gradle
app/src/androidTest/java/tech/relaycorp/courier/ExampleInstrumentedTest.kt
app/src/test/java/tech/relaycorp/courier/ExampleUnitTest.kt
build.gradle

chore: Configure CI

---

app/build.gradle
app/src/main/java/tech/relaycorp/courier/data/model/StorageUsage.kt
app/src/main/java/tech/relaycorp/courier/data/network/RAMFMessage.kt
app/src/main/java/tech/relaycorp/courier/domain/GetStorageUsage.kt
app/src/main/java/tech/relaycorp/courier/domain/StoreMessage.kt
app/src/main/java/tech/relaycorp/courier/domain/client/CargoCollection.kt
app/src/main/java/tech/relaycorp/courier/domain/server/ServerConnectionService.kt
app/src/main/java/tech/relaycorp/courier/ui/main/MainActivity.kt
app/src/main/java/tech/relaycorp/courier/ui/main/MainViewModel.kt
app/src/main/java/tech/relaycorp/courier/ui/settings/SettingsViewModel.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/values/strings.xml
app/src/sharedTest/java/tech/relaycorp/courier/test/factory/RAMFMessageFactory.kt
app/src/test/java/tech/relaycorp/courier/data/model/StorageUsageTest.kt
app/src/test/java/tech/relaycorp/courier/domain/GetStorageUsageTest.kt
app/src/test/java/tech/relaycorp/courier/domain/StoreMessageTest.kt
app/src/test/java/tech/relaycorp/courier/ui/main/MainViewModelTest.kt
app/src/test/java/tech/relaycorp/courier/ui/settings/SettingsViewModelTest.kt

- Show message on main screen whenever available storage is low (< 50MB)
- Do not store new messages when they don't fit the available storage

feat: Handle low storage available

---

app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCServer.kt

I forgot that I commented this line to force errors 😅 
Closes #59

fix: CogRPCServer stop

---

.github/workflows/ci.yml
app/firebase-test-lab.yml
tests.yml

This is using robo tests for now. The instrumentation tests are part of #8.

chore(CI): Integrate Firebase Test Lab

---

app/src/main/java/tech/relaycorp/courier/ui/settings/SettingsActivity.kt
app/src/main/java/tech/relaycorp/courier/ui/settings/StorageSlider.kt
app/src/main/res/layout/activity_settings.xml

fix: Slider crash

---

app/src/main/java/tech/relaycorp/courier/ui/settings/SettingsViewModel.kt
app/src/main/java/tech/relaycorp/courier/ui/settings/StorageSlider.kt

The crash was related with a floating point precision comparison 🤷 
Fixes #74

fix: Slider precision crash

---

app/src/main/java/tech/relaycorp/courier/ui/sync/people/PeopleSyncViewModel.kt
app/src/main/res/layout/activity_hotspot_instructions.xml
app/src/main/res/values/strings.xml

fix: handle hotspot disabled during sync

---

app/src/main/java/tech/relaycorp/courier/ui/settings/StorageSlider.kt

fix: slider precision crash on Nexus4

---

app/src/main/java/tech/relaycorp/courier/domain/client/CargoDelivery.kt
app/src/test/java/tech/relaycorp/courier/domain/client/CargoDeliveryTest.kt

fix: Always try to deliver to all recipients

---

app/lint.xml
app/src/main/AndroidManifest.xml

fix: Lock app screen orientation to portrait

---

app/build.gradle
app/src/main/java/tech/relaycorp/courier/data/disk/DiskRepository.kt
app/src/main/java/tech/relaycorp/courier/domain/StoreMessage.kt
app/src/main/java/tech/relaycorp/courier/domain/client/CargoDelivery.kt
app/src/test/java/tech/relaycorp/cogrpc/server/CogRPCServerDeliveryCargoTest.kt
app/src/test/java/tech/relaycorp/cogrpc/server/MockCogRPCServerService.kt
app/src/test/java/tech/relaycorp/courier/domain/client/CargoCollectionTest.kt
app/src/test/java/tech/relaycorp/courier/domain/client/CargoDeliveryTest.kt
relaynet-cogrpc-jvm/build.gradle
relaynet-cogrpc-jvm/src/main/java/tech/relaycorp/relaynet/cogrpc/IOUtils.kt
relaynet-cogrpc-jvm/src/main/java/tech/relaycorp/relaynet/cogrpc/RequestMappers.kt
relaynet-cogrpc-jvm/src/main/java/tech/relaycorp/relaynet/cogrpc/client/CogRPCClient.kt
relaynet-cogrpc-jvm/src/test/java/tech/relaycorp/relaynet/cogrpc/client/CogRPCClientTest.kt

fix: Proper message stream closing and channel shutdown

---

app/src/main/AndroidManifest.xml
app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCConnectionService.kt
app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCServer.kt
app/src/main/java/tech/relaycorp/courier/domain/PrivateSync.kt
app/src/main/java/tech/relaycorp/courier/ui/sync/people/PeopleSyncActivity.kt
app/src/main/java/tech/relaycorp/courier/ui/sync/people/PeopleSyncViewModel.kt
app/src/main/res/layout/activity_people_sync.xml
app/src/main/res/values/strings.xml
app/src/test/java/tech/relaycorp/cogrpc/server/CogRPCServerDeliveryCargoTest.kt

fix: Private sync hanging when there is not space available

---

README.md
app/build.gradle
build.gradle

First draft for the README documentation.

chore: Dev documentation

---

app/src/main/res/layout/activity_hotspot_instructions.xml
app/src/main/res/values/strings.xml

Consider this a draft -- feedback is most welcome!

fix: Update UI messages

---

app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCConnectionService.kt

fix: Avoid crash when delivering ack on already closed stream

---

app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCConnectionService.kt
app/src/test/java/tech/relaycorp/cogrpc/server/CogRPCServerDeliveryCargoTest.kt

Closes #128
I wasn't able to reproduce the issue inside a test, but I could debug and follow the crash path. If you can reproduce the crash more easily @gnarea check if this PR fixes it please.

fix: invalid cargo server crash when call already completed.

---

app/build.gradle
app/src/test/java/tech/relaycorp/cogrpc/server/ClientsConnectedFilterTest.kt
build.gradle

See also: https://github.com/relaycorp/relaynet-gateway-android/pull/57

chore(CI): Actually run test suites

---

app/src/androidTest/java/tech/relaycorp/courier/ui/settings/SettingsActivityTest.kt
app/src/androidTest/java/tech/relaycorp/courier/ui/sync/internet/InternetSyncActivityTest.kt
app/src/main/java/tech/relaycorp/courier/common/di/ViewModelFactory.kt
app/src/main/java/tech/relaycorp/courier/ui/main/MainActivity.kt
app/src/main/java/tech/relaycorp/courier/ui/settings/SettingsActivity.kt
app/src/main/java/tech/relaycorp/courier/ui/sync/internet/InternetSyncActivity.kt
app/src/main/java/tech/relaycorp/courier/ui/sync/people/HotspotInstructionsActivity.kt
app/src/main/java/tech/relaycorp/courier/ui/sync/people/PeopleSyncActivity.kt
app/src/sharedTest/java/tech/relaycorp/courier/test/WaitAssertions.kt
app/src/test/java/tech/relaycorp/cogrpc/server/ClientsConnectedFilterTest.kt
app/src/test/java/tech/relaycorp/courier/ui/main/MainViewModelTest.kt
app/src/test/java/tech/relaycorp/courier/ui/settings/SettingsViewModelTest.kt
app/src/test/java/tech/relaycorp/test/WaitAssertions.kt

chore: Fix flaky unit tests & failing instrumentation tests

---

.github/workflows/ci-cd.yml
app/build.gradle
app/firebase-test-lab.yml
app/src/androidTest/java/tech/relaycorp/courier/data/preference/StoragePreferencesTest.kt
app/src/androidTest/java/tech/relaycorp/courier/domain/PrivateSyncTest.kt
app/src/androidTest/java/tech/relaycorp/courier/ui/main/MainActivityTest.kt
app/src/androidTest/java/tech/relaycorp/courier/ui/settings/SettingsActivityTest.kt
app/src/main/java/tech/relaycorp/cogrpc/server/Networking.kt
app/src/main/java/tech/relaycorp/courier/domain/StoreMessage.kt
app/src/main/java/tech/relaycorp/courier/domain/client/CargoCollection.kt
app/src/main/java/tech/relaycorp/courier/domain/client/CargoDelivery.kt
app/src/sharedTest/java/tech/relaycorp/courier/test/WaitAssertions.kt
app/src/test/java/tech/relaycorp/cogrpc/server/NetworkingTest.kt
app/src/test/java/tech/relaycorp/courier/domain/client/CargoCollectionTest.kt
app/src/test/java/tech/relaycorp/courier/domain/client/CargoDeliveryTest.kt
app/src/test/java/tech/relaycorp/courier/ui/settings/SettingsViewModelTest.kt
build.gradle

Instead of robo tests.
Fixes #177
Fixes #168

chore(CI): Run instrumentation tests on Firebase Test Lab

---

app/src/main/java/tech/relaycorp/cogrpc/server/CogRPCConnectionService.kt

Closes #197
I tried for quite some time to get a test to reproduce the issue, but it's tough race condition to reproduce in a test. But reproducing it live was way easier, and this change fixed the race condition.

fix: Invalid cargo crash

---

app/src/androidTest/java/tech/relaycorp/courier/data/preference/StoragePreferencesTest.kt
app/src/androidTest/java/tech/relaycorp/courier/domain/PrivateSyncTest.kt
app/src/androidTest/java/tech/relaycorp/courier/ui/settings/SettingsActivityTest.kt
app/src/main/java/tech/relaycorp/cogrpc/server/Networking.kt
app/src/main/java/tech/relaycorp/courier/ui/BaseViewModel.kt
app/src/main/java/tech/relaycorp/courier/ui/main/MainViewModel.kt
app/src/main/java/tech/relaycorp/courier/ui/settings/SettingsViewModel.kt
app/src/main/java/tech/relaycorp/courier/ui/sync/internet/InternetSyncViewModel.kt
app/src/main/java/tech/relaycorp/courier/ui/sync/people/PeopleSyncViewModel.kt
app/src/test/java/tech/relaycorp/courier/ui/settings/SettingsViewModelTest.kt
build.gradle

fix: Flaky tests

---

app/src/main/java/tech/relaycorp/courier/domain/PublicSync.kt

To work around https://github.com/cloudflare/cloudflare-docs/issues/565

fix: Use Google's DoH resolver

---

app/build.gradle
build.gradle

fix: Upgrade gRPC dependencies

---

app/src/main/java/tech/relaycorp/courier/App.kt

chore: Disable ActivityLeaks StrictMode

---

app/build.gradle
build.gradle

And make it upgradable by dependabot.

fix: Upgrade room to v2.3.0

---

app/src/androidTest/java/tech/relaycorp/courier/ui/settings/SettingsActivityTest.kt
app/src/main/res/values/strings.xml

fix: Improve copy related to clearing user data

---

README.md
app/build.gradle
app/src/main/java/tech/relaycorp/courier/ui/BaseActivity.kt
app/src/main/res/values/themes.xml

Related to https://github.com/relaycorp/relayverse/issues/45

fix: Require Android 6 or newer

---

app/src/main/java/tech/relaycorp/courier/domain/StoreMessage.kt
app/src/test/java/tech/relaycorp/courier/domain/StoreMessageTest.kt

Closes: https://github.com/relaycorp/relaynet-courier-android/issues/255
In the process I found a bug. Here:
https://github.com/relaycorp/awala-testing-jvm/blob/d057538ede0ebc7636c97152b4da42764bf566ad/src/main/kotlin/tech/relaycorp/relaynet/testing/pki/CDACertPath.kt#L27
It should be `KeyPairSet.PRIVATE_GW.private`. I'll do a PR for that and then incorporate it here.

fix: Verify cargo bound for private gateways

---

app/build.gradle
build.gradle

fix(deps): Update gRPC to 1.61.0
